apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>NGINX Canary Demo</title>
    </head>
    <body>
      <h1>Hello from NGINX ðŸš€</h1>
      <p>This site is running in Kubernetes using Argo Rollouts.</p>
    </body>
    </html>